apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: myd
  name: myd
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: {{ .Values.myservice.nodeport }}
  selector:
    app: myd
  type: {{ .Values.myservice.type }}
status:
  loadBalancer: {}
